// import {categories_Navbar,categories_Navbar2} from "../components/categories.js";

// // console.log(categories_Navbar,categories_Navbar2)
// let viewAll =document.getElementById("clothNavbar")

// viewAll.innerHTML=categories_Navbar()
// console.log(viewAll)

// // import {categories_Navbar2} from "../components/categories.js";

// let viewAll2 =document.getElementById("clothNavbar2")

// viewAll2.innerHTML=categories_Navbar2()
// console.log(viewAll2)


///////////////////////////////

import {men_Mega_navbar} from"../components/mens_mega_navbar.js"

let m= document.getElementById("men-mega-navbar");
m.innerHTML=men_Mega_navbar()
console.log(m)

import {topSearch} from "../components/topnavbar.js"

let t= document.getElementById("top-search");
t.innerHTML=topSearch()
console.log(t)

import {footerBottom} from "../components/footer.js"

let fot=document.getElementById("footerDiv123")
fot.innerHTML=footerBottom()

let Mens_Clothing =

[
    // Men_Clothing

{"name":"541 ASOS DESIGN lounge trousers in woven stripe","price":"15","color":"woven stripe","image":"https://images.asos-media.com/products/asos-design-lounge-trousers-in-woven-stripe/201179743-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"Carhartt WIP vista tie dye socks in purple","price":"21","color":"purple","image":"https://images.asos-media.com/products/carhartt-wip-vista-tie-dye-socks-in-purple/201995418-1-purple?$n_480w$&wid=476&fit=constrain"},
{"name":"124 ASOS DESIGN regular revere viscose shirt in bright blue","color":" bright blue","price":"22","image":"https://images.asos-media.com/products/asos-design-regular-revere-viscose-shirt-in-bright-blue/202440625-1-cobaltblue?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN boxy oversized shirt in yellow and pink painted check","color":"yellow and pink","price":"26","image":"https://images.asos-media.com/products/asos-design-boxy-oversized-shirt-in-yellow-and-pink-painted-check/202579390-1-yellow?$n_480w$&wid=476&fit=constrain"},
{"name":"476 Abercrombie & Fitch back gel logo heavyweight oversized t-shirt in white","color":"white","price":"29","image":"https://images.asos-media.com/products/abercrombie-fitch-back-gel-logo-heavyweight-oversized-t-shirt-in-white/202851446-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"68 Hollister 5 pack central script logo stripe & plain t-shirt in multi","color":"multi","price":"65","image":"https://images.asos-media.com/products/hollister-5-pack-central-script-logo-stripe-plain-t-shirt-in-multi/202801389-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"Hollister icon logo stripe & contrast collar polo in white","price":"25","color":"white","image":"https://images.asos-media.com/products/hollister-icon-logo-stripe-contrast-collar-polo-in-white/202801301-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"Hollister outdoors central logo print t-shirt in black","price":"19","color":"black","image":"https://images.asos-media.com/products/hollister-outdoors-central-logo-print-t-shirt-in-black/202800542-1-blackwred?$n_480w$&wid=476&fit=constrain"},
{"name":"Hollister outdoors central & back logo print t-shirt in white","price":"19","color":"","image":"https://images.asos-media.com/products/hollister-outdoors-central-back-logo-print-t-shirt-in-white/202800428-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons vest with Paradise back print in navy","price":"15","color":"navy","image":"https://images.asos-media.com/products/only-sons-vest-with-paradise-back-print-in-navy/202729846-1-darknavy?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons vest with mandala back print in white","price":"15","color":" white","image":"https://images.asos-media.com/products/only-sons-vest-with-mandala-back-print-in-white/202729794-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons vest with Seoul back print in black","price":"15","color":"black","image":"https://images.asos-media.com/products/only-sons-vest-with-seoul-back-print-in-black/202729310-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Abercrombie & Fitch 3D icon logo slim fit pique polo in red","price":"35","color":"red","image":"https://images.asos-media.com/products/abercrombie-fitch-3d-icon-logo-slim-fit-pique-polo-in-red/202666080-1-red?$n_480w$&wid=476&fit=constrain"},
{"name":"Abercrombie & Fitch 3D icon logo slim fit pique polo in green","price":"35","color":"green","image":"https://images.asos-media.com/products/abercrombie-fitch-3d-icon-logo-slim-fit-pique-polo-in-green/202666051-1-green?$n_480w$&wid=476&fit=constrain"},
{"name":"Abercrombie & Fitch 3D icon logo slim fit pique polo shirt in light blue","price":"35","color":"light blue","image":"https://images.asos-media.com/products/asos-design-skinny-denim-shacket-in-light-wash/201370677-1-lightblue?$n_480w$&wid=476&fit=constrain"},
{"name":"Abercrombie & Fitch 3D icon logo slim fit pique polo shirt in light blue","price":"35","color":"light blue","image":"https://images.asos-media.com/products/abercrombie-fitch-3d-icon-logo-slim-fit-pique-polo-shirt-in-light-blue/202666035-1-lightblue?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons revere shirt in aztec print","price":"26","color":"aztec ","image":"https://images.asos-media.com/products/only-sons-revere-shirt-in-aztec-print/202626467-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons revere shirt in checkerboard print","price":"26","color":"aztec ","image":"https://images.asos-media.com/products/only-sons-revere-shirt-in-checkerboard-print/202626246-1-pomegranite?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons revere shirt with flower border print in navy","price":"26","color":"navy","image":"https://images.asos-media.com/products/only-sons-revere-shirt-with-flower-border-print-in-navy/202626238-1-darknavy?$n_480w$&wid=476&fit=constrain"},
{"name":"Only & Sons knitted stripe t-shirt in navy and white","price":"26","color":"navy and white","image":"https://images.asos-media.com/products/only-sons-knitted-stripe-t-shirt-in-navy-and-white/202624710-1-darknavy?$n_480w$&wid=476&fit=constrain"},
{"name":"Carhartt WIP pocket t-shirt in white","price":"37","color":"white","image":"https://images.asos-media.com/products/carhartt-wip-pocket-t-shirt-in-white/202587946-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"251 ASOS DESIGN relaxed revere shirt in vintage inspired floral print","price":"27","color":"light blue","image":"https://images.asos-media.com/products/asos-design-skinny-denim-shirt-with-rips-in-light-blue/201607270-1-blue?$n_480w$&wid=476&fit=constrain"},
{"name":"New Era New York Yankees oversized t-shirt in lilac","price":"32","color":"lilac","image":"https://images.asos-media.com/products/new-era-new-york-yankees-oversized-t-shirt-in-lilac/202122253-1-purple?$n_480w$&wid=476&fit=constrain"},
{"name":"Hollister outdoors central & back logo print t-shirt in white","price":"19","color":"","image":"https://images.asos-media.com/products/hollister-outdoors-central-back-logo-print-t-shirt-in-white/202800428-1-white?$n_480w$&wid=476&fit=constrain"},

//  Accessories
{"name":"Levi's woodmark beanie with modern vintage logo in black","price":"30","color":"Black","image":"https://images.asos-media.com/products/levis-woodmark-beanie-with-modern-vintage-logo-in-black/200825068-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Calvin Klein large icon logo wallet in black","price":"69","color":"Black Mono","image":"https://images.asos-media.com/products/calvin-klein-large-icon-logo-wallet-in-black/202359274-1-blackmono?$n_480w$&wid=476&fit=constrain"},
{"name":"Calvin Klein all over monogram crossbody in black","price":"63","color":" Black Uv Mono","image":"https://images.asos-media.com/products/calvin-klein-all-over-monogram-crossbody-in-black/202359289-1-blackuvmono?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN textured belt in cow print","price":"15","color":"Multi","image":"https://images.asos-media.com/products/asos-design-textured-belt-in-cow-print/201361702-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"Nike H86 Futura washed cotton cap in stone","price":"19","color":"Stone","image":"https://images.asos-media.com/products/nike-h86-futura-washed-cotton-cap-in-stone/200850212-1-stone?$n_480w$&wid=476&fit=constrain"},
{"name":"Polo Ralph Lauren logo baseball cap in beige","price":"48","color":"Beige","image":"https://images.asos-media.com/products/polo-ralph-lauren-logo-baseball-cap-in-beige/202383029-1-beige?$n_480w$&wid=476&fit=constrain"},
{"name":"Icon Brand stainless steel mariner figaro necklace in gold","price":"25","color":"Gold","image":"https://images.asos-media.com/products/icon-brand-stainless-steel-mariner-figaro-necklace-in-gold/201853466-1-gold?$n_480w$&wid=476&fit=constrain"},
{"name":"51 Carhartt WIP harlem cord cap in green","price":"37","color":"Green","image":"https://images.asos-media.com/products/carhartt-wip-harlem-cord-cap-in-green/201995436-1-green?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN recycled frame square sunglasses in black with solid black lens","price":"9","color":"Black","image":"https://images.asos-media.com/products/asos-design-recycled-frame-square-sunglasses-in-black-with-solid-black-lens/23132982-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN leather slim belt in black with square silver buckle","price":"15","color":"Black","image":"https://images.asos-media.com/products/asos-design-leather-slim-belt-in-black-with-square-silver-buckle/200763015-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN recycled slim tie with ombre effect pocket square in stone","price":"12","color":"STONE","image":"https://images.asos-media.com/products/asos-design-recycled-slim-tie-with-ombre-effect-pocket-square-in-stone/201683071-1-stone?$n_480w$&wid=476&fit=constrain"},
{"name":"South Beach Man cap with side logo in black","price":"11","color":"Black","image":"https://images.asos-media.com/products/south-beach-man-cap-with-side-logo-in-black/201827964-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN satin slim tie & pocket square in burgundy","price":"15","color":"Burgundy","image":"https://images.asos-media.com/products/asos-design-satin-slim-tie-pocket-square-in-burgundy/23379234-1-burgundy?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN slim figaro neckchain in silver tone","price":"7","color":"Silver","image":"https://images.asos-media.com/products/asos-design-slim-figaro-neckchain-in-silver-tone/14775305-1-silver?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN 4 pack leather and woven bracelet set in monochrome","price":"9","color":"Black","image":"https://images.asos-media.com/products/asos-design-4-pack-leather-and-woven-bracelet-set-in-monochrome/202185503-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"SELLING FAST Casio mini digital watch in silver tone LA670WEA-7EF","price":"32","color":"Silver tone","image":"https://images.asos-media.com/products/casio-mini-digital-watch-in-silver-tone-la670wea-7ef/2394649-1-silvertone?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN 9mm hoop earrings in real silver plate","price":"9","color":"Silver","image":"https://images.asos-media.com/products/asos-design-9mm-hoop-earrings-in-real-silver-plate/22049434-1-silver?$n_480w$&wid=476&fit=constrain"},
{"name":"86 New Look puff sleeve corset top in black","price":"19","color":"Black","image":"https://images.asos-media.com/products/new-look-puff-sleeve-corset-top-in-black/203057379-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"New Look ditsy lace vest in white pattern","price":"10","color":"White","image":"https://images.asos-media.com/products/new-look-ditsy-lace-vest-in-white-pattern/203054103-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"New Look tall floral split midi skirt in black","price":"22","color":"Black Floral","image":"https://images.asos-media.com/products/new-look-tall-floral-split-midi-skirt-in-black/203019735-1-blackfloral?$n_480w$&wid=476&fit=constrain"},

//shoes

{"name":"Polo Ralph Lauren court trainer in white/green with pony logo","price":"90","color":"MULTI","image":"https://images.asos-media.com/products/polo-ralph-lauren-court-trainer-in-white-green-with-pony-logo/201879757-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"Levi's square high trainer with red tab in white","price":"70","color":"WHITE","image":"https://images.asos-media.com/products/levis-square-high-trainer-with-red-tab-in-white/202363011-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"57 Polo Ralph Lauren trackster 200II sock trainer in cream/ grey with pony tongue logo","price":"137","color":"CREAM","image":"https://images.asos-media.com/products/polo-ralph-lauren-trackster-200ii-sock-trainer-in-cream-grey-with-pony-tongue-logo/201896631-1-cream?$n_480w$&wid=476&fit=constrain"},
{"name":"Polo Ralph Lauren trackster leather trainer with pony logo in blue suede","price":"126","color":"BLUE","image":"https://images.asos-media.com/products/polo-ralph-lauren-trackster-leather-trainer-with-pony-logo-in-blue-suede/201896394-1-blue?$n_480w$&wid=476&fit=constrain"},
{"name":"Polo Ralph Lauren court trainer in white/green with pony logo","price":"90","color":"MULTI","image":"https://images.asos-media.com/products/polo-ralph-lauren-court-trainer-in-white-green-with-pony-logo/201879757-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"Asra Foza chain loafers in brown suede","price":"65","color":" BROWN","image":"https://images.asos-media.com/products/asra-foza-chain-loafers-in-brown-suede/201916910-1-brown?$n_480w$&wid=476&fit=constrain"},
{"name":"adidas Originals Court Rallye slip on trainers in black","price":"34","color":"Black","image":"https://images.asos-media.com/products/adidas-originals-court-rallye-slip-on-trainers-in-black/22978509-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"271 Walk London Benjamin snaffle sandals in black leather","price":"65","color":"Black","image":"https://images.asos-media.com/products/walk-london-benjamin-snaffle-sandals-in-black-leather/201504864-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Vans Era Tie Dye trainers in orange","price":"38","color":"Bandana tie dyeorang","image":"https://images.asos-media.com/products/vans-era-tie-dye-trainers-in-orange/23440771-1-bandanatiedyeorang?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman grey piper emboss tassel loafers","price":"16","color":"Grey","image":"https://images.asos-media.com/products/topman-grey-piper-emboss-tassel-loafers/203080750-1-grey?$n_480w$&wid=476&fit=constrain"},
{"name":"Nike Victori One sliders in wheat/brown","price":"27","color":"Brown","image":"https://images.asos-media.com/products/nike-victori-one-sliders-in-wheat-brown/201493267-1-brown?$n_480w$&wid=476&fit=constrain"},
{"name":"Nike Air Max Dawn trainers in white/malachite","price":"104","color":" White/Green","image":"https://images.asos-media.com/products/nike-air-max-dawn-trainers-in-white-malachite/201492129-1-whitegreen?$n_480w$&wid=476&fit=constrain"},
{"name":"Schuh reuben lace up shoes in brown leather","price":"49","color":"Brown","image":"https://images.asos-media.com/products/schuh-reuben-lace-up-shoes-in-brown-leather/202041819-1-brown?$n_480w$&wid=476&fit=constrain"},
{"name":"Havaianas Brasil logo flip flops in navy","price":"26","color":"NAVY","image":"https://images.asos-media.com/products/havaianas-brasil-logo-flip-flops-in-navy/201647277-1-navy?$n_480w$&wid=476&fit=constrain"},
{"name":"Walk London Riva snaffle loafers in beige suede","price":"75","color":"NEUTRAL","image":"https://images.asos-media.com/products/walk-london-riva-snaffle-loafers-in-beige-suede/201587799-1-neutral?$n_480w$&wid=476&fit=constrain"},
{"name":"Walk London Terry Snaffle loafers in pink suede","price":"65","color":"Pink","image":"https://images.asos-media.com/products/walk-london-terry-snaffle-loafers-in-pink-suede/201507718-1-pink?$n_480w$&wid=476&fit=constrain"},
{"name":"adidas Running Questar trainers in grey and blue","price":"74","color":"Grey","image":"https://images.asos-media.com/products/adidas-running-questar-trainers-in-grey-and-blue/202662296-1-grey?$n_480w$&wid=476&fit=constrain"},
{"name":"158 adidas Originals Geodiver Primeblue trainers in crystal white","price":"75","color":"White","image":"https://images.asos-media.com/products/adidas-originals-geodiver-primeblue-trainers-in-crystal-white/201270974-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"Buffalo cloud corin chain vegan trainers in black","price":"110","color":"Black","image":"https://images.asos-media.com/products/buffalo-cloud-corin-chain-vegan-trainers-in-black/201297176-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Clarks Originals desert coal boots in green camo","price":"13","color":"","image":"https://images.asos-media.com/products/clarks-originals-desert-coal-boots-in-green-camo/201243339-1-green?$n_480w$&wid=476&fit=constrain"},
{"name":"Clarks Originals desert coal boots in green camo","price":"130","color":"Green","image":"https://images.asos-media.com/products/clarks-originals-desert-coal-boots-in-green-camo/201243339-1-green?$n_480w$&wid=476&fit=constrain"},
{"name":"237 ASOS DESIGN mule loafer in black faux leather with embossed detail","price":"40","color":"Black","image":"https://images.asos-media.com/products/asos-design-mule-loafer-in-black-faux-leather-with-embossed-detail/201129199-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"River Island weave wallet in black","price":"19","color":"BLACK","image":"https://images.asos-media.com/products/river-island-weave-wallet-in-black/202999009-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Rains 1382 box bag micro in blue river","price":"59","color":"River","image":"https://images.asos-media.com/products/rains-1382-box-bag-micro-in-blue-river/201576921-1-river?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN faux leather weave wallet in bright green","price":"13","color":"MID GREEN","image":"https://images.asos-media.com/products/asos-design-faux-leather-weave-wallet-in-bright-green/201606852-1-midgreen?$n_480w$&wid=476&fit=constrain"},
{"name":"River Island weave reversible belt in black","price":"19","color":"BLACK","image":"https://images.asos-media.com/products/river-island-weave-reversible-belt-in-black/202999012-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN textured belt in cow print","price":"15","color":"MULTI","image":"https://images.asos-media.com/products/asos-design-textured-belt-in-cow-print/201361702-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN leather wide belt in black with matte black buckle","price":"17","color":"Black","image":"https://images.asos-media.com/products/asos-design-leather-wide-belt-in-black-with-matte-black-buckle/24148581-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Bag red","price":"18","color":"Purple","image":"https://images.asos-media.com/products/nike-running-slim-waistpack-in-purple/201363798-1-purple?$n_480w$&wid=476&fit=constrain"},{"name":"Nike Heritage waistpack in green","price":"18","color":"Green","image":"https://images.asos-media.com/products/nike-heritage-waistpack-in-green/201432226-1-green?$n_480w$&wid=476&fit=constrain"},{"name":"Timberland Logo bum bag in black","price":"30","color":"Black","image":"https://images.asos-media.com/products/timberland-logo-bum-bag-in-black/201705753-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Dickies Blanchard bumbag in lilac","price":"25","color":"LILAC","image":"https://images.asos-media.com/products/dickies-blanchard-bumbag-in-lilac/202776122-1-lilac?$n_480w$&wid=476&fit=constrain"},
{"name":"River Island weave wallet in black","price":"19","color":"BLACK","image":"https://images.asos-media.com/products/river-island-weave-wallet-in-black/202999009-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"River Island monogram wallet in black","price":"19","color":"BLACK","image":"https://images.asos-media.com/products/river-island-monogram-wallet-in-black/202999013-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"The North Face Bozer III cross body bag in black","price":"32","color":"Black","image":"https://images.asos-media.com/products/the-north-face-bozer-iii-cross-body-bag-in-black/23429687-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"The North Face Jester crossbody bag in black","price":"30","color":"Black","image":"https://images.asos-media.com/products/the-north-face-jester-crossbody-bag-in-black/201761032-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Fred Perry pique textured billfold wallet in black","price":"50","color":"BLACK","image":"https://images.asos-media.com/products/fred-perry-pique-textured-billfold-wallet-in-black/202060362-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"adidas Training 3 Stripe backpack in grey","price":"30","color":"GREY","image":"https://images.asos-media.com/products/adidas-training-3-stripe-backpack-in-grey/201323629-1-grey?$n_480w$&wid=476&fit=constrain"},{"name":"adidas Originals adicolor Trefoil backpack in black","price":"23","color":"Black","image":"https://images.asos-media.com/products/adidas-originals-adicolor-trefoil-backpack-in-black/24312425-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"The North Face Rodey backpack in black","price":"63","color":" Tnf black","image":"https://images.asos-media.com/products/the-north-face-rodey-backpack-in-black/14927859-1-tnfblack?$n_480w$&wid=476&fit=constrain"},
{"name":"Rains 1382 box bag micro in blue river","price":"59","color":"River","image":"https://images.asos-media.com/products/rains-1382-box-bag-micro-in-blue-river/201576921-1-river?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN faux leather weave wallet in bright green","price":"13","color":"MID GREEN","image":"https://images.asos-media.com/products/asos-design-faux-leather-weave-wallet-in-bright-green/201606852-1-midgreen?$n_480w$&wid=476&fit=constrain"},
{"name":"Calvin Klein Jeans monogram hardware 35mm reversible belt in brown/black","price":"58","color":"BLACK","image":"https://images.asos-media.com/products/calvin-klein-jeans-monogram-hardware-35mm-reversible-belt-in-brown-black/202404291-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN slim leather belt with burnished edge in brown","price":"13","color":"BROWN","image":"https://images.asos-media.com/products/asos-design-slim-leather-belt-with-burnished-edge-in-brown/202079038-1-brown?$n_480w$&wid=476&fit=constrain"},{"name":"River Island casual leather belt in brown","price":"19","color":"BROWN - DARK","image":"https://images.asos-media.com/products/river-island-casual-leather-belt-in-brown/202673820-1-browndark?$n_480w$&wid=476&fit=constrain"},
{"name":"River Island weave reversible belt in black","price":"19","color":"BLACK","image":"https://images.asos-media.com/products/river-island-weave-reversible-belt-in-black/202999012-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN textured belt in cow print","price":"15","color":"MULTI","image":"https://images.asos-media.com/products/asos-design-textured-belt-in-cow-print/201361702-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"BOSS Rudy leather belt in black","price":"73","color":"Black","image":"https://images.asos-media.com/products/boss-rudy-leather-belt-in-black/201881027-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"adidas Golf reversible web belt in black and grey","price":"15","color":"MULTI","image":"https://images.asos-media.com/products/adidas-golf-reversible-web-belt-in-black-and-grey/201280579-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN slim webbing belt with plate buckle detail","price":"7","color":"Black","image":"https://images.asos-media.com/products/asos-design-slim-webbing-belt-with-plate-buckle-detail/21799891-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Calvin Klein new monogram belt in black","price":"55","color":"Black","image":"https://images.asos-media.com/products/calvin-klein-new-monogram-belt-in-black/201590739-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN leather wide belt in black with matte black buckle","price":"17","color":"Black","image":"https://images.asos-media.com/products/asos-design-leather-wide-belt-in-black-with-matte-black-buckle/24148581-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Sunday Rain Sleep Easy Body Scrub 265g","price":"7","color":"No Colour","image":"https://images.asos-media.com/products/sunday-rain-sleep-easy-body-scrub-265g/202314314-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"St. Tropez Self Tan 50ml Purity Water Mousse and Face Mist Mini Kit","price":"16","color":" No colour","image":"https://images.asos-media.com/products/st-tropez-self-tan-50ml-purity-water-mousse-and-face-mist-mini-kit/14558277-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"The Ordinary 4% Sulphate Cleanser for Body and Hair 240ml","price":"8","color":"NO COLOUR","image":"https://images.asos-media.com/products/the-ordinary-4-sulphate-cleanser-for-body-and-hair-240ml/202332500-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"LUSH Big Hugs Bath Bomb Duo Set","price":"12","color":" No Colour","image":"https://images.asos-media.com/products/lush-big-hugs-bath-bomb-duo-set/202812330-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Garnier Summer Body Hydrating Gradual Tan Moisturiser Light 400ml","price":"8","color":"No colour","image":"https://images.asos-media.com/products/garnier-summer-body-hydrating-gradual-tan-moisturiser-light-400ml/20639673-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Bondi Sands Summer Fruits Body Wash 500ml","price":"9","color":" NO COLOUR","image":"https://images.asos-media.com/products/bondi-sands-summer-fruits-body-wash-500ml/201873168-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"L'Oreal Men Expert Total Clean Shower Gel 300ml","price":"4","color":"Multi","image":"https://images.asos-media.com/products/loreal-men-expert-total-clean-shower-gel-300ml/8867569-1-multi?$n_480w$&wid=476&fit=constrain"},
{"name":"Miss Patisserie Harmony Bath Ball with Amethyst Crystals","price":"5","color":"No colour","image":"https://images.asos-media.com/products/miss-patisserie-harmony-bath-ball-with-amethyst-crystals/21975832-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"St. Tropez Self Tan Purity Face Mist 80ml","price":"24","color":"Purity face mist","image":"https://images.asos-media.com/products/st-tropez-self-tan-purity-face-mist-80ml/9560010-1-purityfacemist?$n_480w$&wid=476&fit=constrain"},{"name":"Bondi Sands Summer Fruits Body Moisturiser 500ml","price":"11","color":" NO COLOUR","image":"https://images.asos-media.com/products/bondi-sands-summer-fruits-body-moisturiser-500ml/201873092-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Miss Patisserie Vanilla Fig Bath Slab","price":"5","color":"No colour","image":"https://images.asos-media.com/products/miss-patisserie-vanilla-fig-bath-slab/21995847-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Sunday Rain Body Butter Mango & Coconut","price":"9","color":"No colour","image":"https://images.asos-media.com/products/sunday-rain-body-butter-mango-coconut/20085352-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"L'Oreal Paris Men Expert Barber's Essentials Beard Grooming Duo Set for him","price":"19","color":"No Colour","image":"https://images.asos-media.com/products/loreal-paris-men-expert-barbers-essentials-beard-grooming-duo-set-for-him/202859914-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"The INKEY List 15% Vitamin C and EGF Serum 30ml","price":"16","color":"No Colour","image":"https://images.asos-media.com/products/the-inkey-list-15-vitamin-c-and-egf-serum-30ml/202549675-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Bondi Sands Summer Fruits Body Moisturiser 500ml","price":"10","color":"No Colour","image":"https://images.asos-media.com/products/bondi-sands-summer-fruits-body-moisturiser-500ml/201873092-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Bondi Sands Summer Fruits Coconut & Sea Salt Body Scrub 250g","price":"14","color":"No Colour","image":"https://images.asos-media.com/products/bondi-sands-summer-fruits-coconut-sea-salt-body-scrub-250g/201873152-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Bondi Sands Summer Fruits Body Wash 500ml","price":"9","color":"No Colour","image":"https://images.asos-media.com/products/bondi-sands-summer-fruits-body-wash-500ml/201873168-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Elemis Pro-Collagen Night Cream 30ml","price":"67","color":"NO COLOUR","image":"https://images.asos-media.com/products/elemis-pro-collagen-night-cream-30ml/202730822-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"185 BaBylissMEN Powerblade Pro Hair Clipper","price":"32","color":" Powerblade pro","image":"https://images.asos-media.com/products/babylissmen-powerblade-pro-hair-clipper/21066017-1-powerbladepro?$n_480w$&wid=476&fit=constrain"},
{"name":"Gillette SkinGuard Sensitive Razor Blades - 4 Pack","price":"13","color":"No Colour","image":"https://images.asos-media.com/products/gillette-skinguard-sensitive-razor-blades-4-pack/13723012-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"185 Wahl Groomsman 8 in 1 Trimmer Kit","price":"20","color":"No Colour","image":"https://images.asos-media.com/products/wahl-groomsman-8-in-1-trimmer-kit/201714304-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Issey Miyake L'Eau d'Issey pour Homme Eau de Toilette Igo Cap 20ml","price":"24","color":"No Colour","image":"https://images.asos-media.com/products/issey-miyake-leau-dissey-pour-homme-eau-de-toilette-igo-cap-20ml/202440922-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Narciso Rodriguez Narciso Eau de Parfum Rouge 90ml","price":"92","color":"No Colour","image":"https://images.asos-media.com/products/narciso-rodriguez-narciso-eau-de-parfum-rouge-90ml/202440926-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Revolution Man Niacinamide Serum 30ml","price":"9","color":" No Colour","image":"https://images.asos-media.com/products/revolution-man-niacinamide-serum-30ml/202883572-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Revolution Man Niacinamide Serum 30ml","price":"9","color":" No Colour","image":"https://images.asos-media.com/products/revolution-man-niacinamide-serum-30ml/202883572-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Revolution Man Energise Brightening Anti-Fatigue Serum 30ml","price":"11","color":" No Colour","image":"https://images.asos-media.com/products/revolution-man-energise-brightening-anti-fatigue-serum-30ml/202883570-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Garnier Vitamin C Brightening Essentials Set (save 33%)","price":"13","color":" NO COLOUR","image":"https://images.asos-media.com/products/garnier-vitamin-c-brightening-essentials-set-save-33/202531106-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"The INKEY List 15% Vitamin C and EGF Serum 30ml","price":"16","color":" NO COLOUR","image":"https://images.asos-media.com/products/the-inkey-list-15-vitamin-c-and-egf-serum-30ml/202549675-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"St.Tropez Gradual Tan Classic Light/Medium 200ml","price":"18","color":" NO COLOUR","image":"https://images.asos-media.com/products/sttropez-gradual-tan-classic-light-medium-200ml/201775188-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Philip Kingsley Body & Volume Discovery Kit","price":"21","color":"No Colour","image":"https://images.asos-media.com/products/philip-kingsley-body-volume-discovery-kit/202523046-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Philip Kingsley Flake Free Discovery Kit","price":"24","color":"No Colour","image":"https://images.asos-media.com/products/philip-kingsley-flake-free-discovery-kit/202523041-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Revolution Man Niacinamide Serum 30ml","price":"9","color":" No Colour","image":"https://images.asos-media.com/products/revolution-man-niacinamide-serum-30ml/202883572-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Revolution Man Niacinamide Serum 30ml","price":"9","color":" No Colour","image":"https://images.asos-media.com/products/revolution-man-niacinamide-serum-30ml/202883572-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Revolution Man Energise Brightening Anti-Fatigue Serum 30ml","price":"11","color":" No Colour","image":"https://images.asos-media.com/products/revolution-man-energise-brightening-anti-fatigue-serum-30ml/202883570-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"Garnier Vitamin C Brightening Essentials Set (save 33%)","price":"13","color":" NO COLOUR","image":"https://images.asos-media.com/products/garnier-vitamin-c-brightening-essentials-set-save-33/202531106-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"The INKEY List 15% Vitamin C and EGF Serum 30ml","price":"16","color":" NO COLOUR","image":"https://images.asos-media.com/products/the-inkey-list-15-vitamin-c-and-egf-serum-30ml/202549675-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"Uppercut Deluxe Sea Salt Spray","price":"15","color":"Sea salt spray","image":"https://images.asos-media.com/products/uppercut-deluxe-sea-salt-spray/20613715-1-seasaltspray?$n_480w$&wid=476&fit=constrain"},{"name":"Uppercut Deluxe Pomade","price":"18","color":"Multi","image":"https://images.asos-media.com/products/uppercut-deluxe-pomade/6402874-1-multi?$n_480w$&wid=476&fit=constrain"},{"name":"Uppercut Deluxe Monster Hold Wax","price":"18","color":"Multi","image":"https://images.asos-media.com/products/uppercut-deluxe-monster-hold-wax/6403897-1-multi?$n_480w$&wid=476&fit=constrain"},{"name":"The INKEY List Salicylic Acid Exfoliating Scalp Treatment 150ml","price":"16","color":"NO COLOUR","image":"https://images.asos-media.com/products/the-inkey-list-salicylic-acid-exfoliating-scalp-treatment-150ml/201137991-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"The INKEY List Caffeine Stimulating Scalp Treatment 150ml","price":"16","color":"NO COLOUR","image":"https://images.asos-media.com/products/the-inkey-list-caffeine-stimulating-scalp-treatment-150ml/201137955-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"The INKEY List Peptide Volumizing Hair Treatment 100ml","price":"14","color":" NO COLOUR","image":"https://images.asos-media.com/products/the-inkey-list-peptide-volumizing-hair-treatment-100ml/201137962-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"https://images.asos-media.com/products/olaplex-no-3-hair-perfector-jumbo-85oz-250ml/201220160-1-jumbono3?$n_480w$&wid=476&fit=constrain","price":"52","color":"Jumbo No.3","image":"https://images.asos-media.com/products/olaplex-no-3-hair-perfector-jumbo-85oz-250ml/201220160-1-jumbono3?$n_480w$&wid=476&fit=constrain"},
{"name":"Olaplex No.4 Bond Maintenance Shampoo 8.5oz/250ml","price":"28","color":"No.4","image":"https://images.asos-media.com/products/olaplex-no4-bond-maintenance-shampoo-85oz-250ml/20626276-1-no4?$n_480w$&wid=476&fit=constrain"},{"name":"Olaplex No.5 Bond Maintenance Conditioner 8.5oz/250ml","price":"28","color":"No.5","image":"https://images.asos-media.com/products/olaplex-no5-bond-maintenance-conditioner-85oz-250ml/20626274-1-no5?$n_480w$&wid=476&fit=constrain"},{"name":"Hanz De Fuko Dry Shampoo","price":"26","color":"No colour","image":"https://images.asos-media.com/products/hanz-de-fuko-dry-shampoo/10001166-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"https://images.asos-media.com/products/we-are-paradoxx-volume-conditioner-250ml/200908211-1-nocolour?$n_480w$&wid=476&fit=constrain","price":"21","color":"NO COLOUR","image":"https://images.asos-media.com/products/we-are-paradoxx-volume-conditioner-250ml/200908211-1-nocolour?$n_480w$&wid=476&fit=constrain"},{"name":"We Are Paradoxx Moisture Mask 200ml","price":"32","color":"We Are Paradoxx Moisture Mask 200ml","image":"https://images.asos-media.com/products/we-are-paradoxx-moisture-mask-200ml/200908201-1-nocolour?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN 90s oversized cord shirt in rust - ORANGE","price":"22","color":"RUST","image":"https://images.asos-media.com/products/asos-design-90s-oversized-cord-shirt-in-rust-orange/200914961-1-rust?$n_480w$&wid=476&fit=constrain"},{"name":"The North Face Collage t-shirt in cream Exclusive at ASOS","price":"27","color":"Cream","image":"https://images.asos-media.com/products/the-north-face-collage-t-shirt-in-cream-exclusive-at-asos/201677619-1-cream?$n_480w$&wid=476&fit=constrain"},{"name":"Nike Club t-shirt in light orewood brown","price":"18","color":"Stone","image":"https://images.asos-media.com/products/nike-club-t-shirt-in-light-orewood-brown/201512219-1-stone?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN 90s oversized cord shirt in rust - ORANGE","price":"22","color":"RUST","image":"https://images.asos-media.com/products/asos-design-90s-oversized-cord-shirt-in-rust-orange/200914961-1-rust?$n_480w$&wid=476&fit=constrain"},{"name":"Topman revere seersucker shirt in check","price":"37","color":"CHECK","image":"https://images.asos-media.com/products/topman-revere-seersucker-shirt-in-check/201508727-1-check?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN co-ord boxy oversized shirt in heavy cotton twill","price":"30","color":" LIGHT BLUE","image":"https://images.asos-media.com/products/asos-design-co-ord-boxy-oversized-shirt-in-heavy-cotton-twill/201779954-1-lightblue?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN 90s oversized cord shirt in pink","price":"27","color":"Pink","image":"https://images.asos-media.com/products/asos-design-90s-oversized-cord-shirt-in-pink/20774925-1-pink?$n_480w$&wid=476&fit=constrain"},{"name":"New Look long sleeve oxford shirt in khaki","price":"18","color":"Khaki","image":"https://images.asos-media.com/products/new-look-long-sleeve-oxford-shirt-in-khaki/200757244-1-khaki?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN relaxed revere shirt in light base floral","price":"22","color":"WHITE","image":"https://images.asos-media.com/products/asos-design-relaxed-revere-shirt-in-light-base-floral/202579432-1-white?$n_480w$&wid=476&fit=constrain"},{"name":"Topman knitted splice zip polo in blue","price":"30","color":"Blue","image":"https://images.asos-media.com/products/topman-knitted-splice-zip-polo-in-blue/201805761-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN regular sheer shirt with ruffle front detail in lilac","price":"30","color":"LILAC","image":"https://images.asos-media.com/products/asos-design-regular-sheer-shirt-with-ruffle-front-detail-in-lilac/201921650-1-lilac?$n_480w$&wid=476&fit=constrain"},
{"name":"Barbour Harris tartan shirt in light blue","price":"70","color":"Blue","image":"https://images.asos-media.com/products/barbour-harris-tartan-shirt-in-light-blue/202252444-1-blue?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN relaxed revere shirt in orange summer stripe","price":"20","color":"ORANGE","image":"https://images.asos-media.com/products/asos-design-relaxed-revere-shirt-in-orange-summer-stripe/202374990-1-orange?$n_480w$&wid=476&fit=constrain"},{"name":"Topman 2 pack formal shirt in black / white","price":"37","color":"BLACK AND WHITE","image":"https://images.asos-media.com/products/topman-2-pack-formal-shirt-in-black-white/202445548-1-blackandwhite?$n_480w$&wid=476&fit=constrain"},{"name":"Bershka grandad shirt with long sleeves in white","price":"25","color":"White","image":"https://images.asos-media.com/products/bershka-grandad-shirt-with-long-sleeves-in-white/202465635-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN relaxed shirt in recycled blend crinkle lightweight fabric in brown","price":"20","color":"BROWN","image":"https://images.asos-media.com/products/asos-design-relaxed-shirt-in-recycled-blend-crinkle-lightweight-fabric-in-brown/201842101-1-brown?$n_480w$&wid=476&fit=constrain"},
{"name":"Jack & Jones Originals oversized revere shirt in white","price":"19","color":"WHITE","image":"https://images.asos-media.com/products/jack-jones-originals-oversized-revere-shirt-in-white/201860630-1-white?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN relaxed shirt in linen mix symbol print","price":"28","color":"MULTI","image":"https://images.asos-media.com/products/asos-design-relaxed-shirt-in-linen-mix-symbol-print/201866549-1-multi?$n_480w$&wid=476&fit=constrain"},{"name":"New Look oversized short sleeve satin shirt in off white","price":"23","color":" Off White","image":"https://images.asos-media.com/products/new-look-oversized-short-sleeve-satin-shirt-in-off-white/202933664-1-offwhite?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman cord western jacket in black washed print","price":"60","color":"black wash","image":"https://images.asos-media.com/products/topman-cord-western-jacket-in-black-washed-print/201270566-1-blackwash?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN oversized checked shacket with contrast collar in stone","price":"58","color":"STONE","image":"https://images.asos-media.com/products/asos-design-oversized-checked-shacket-with-contrast-collar-in-stone/201840794-1-stone?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN regular satin shirt with 70s ruffle front in blue","price":"34","color":"LIGHT BLUE","image":"https://images.asos-media.com/products/asos-design-regular-satin-shirt-with-70s-ruffle-front-in-blue/201921670-1-lightblue?$n_480w$&wid=476&fit=constrain"},
{"name":"Tommy Hilfiger icon logo bold stripe shirt in navy","price":"90","color":"navy","image":"https://images.asos-media.com/products/tommy-hilfiger-icon-logo-bold-stripe-shirt-in-navy/202423285-1-navy?$n_480w$&wid=476&fit=constrain"},{"name":"Polo Ralph Lauren icon logo short sleeve seersucker shirt custom regular fit in indigo blue","price":"79","color":"indigo blue","image":"https://images.asos-media.com/products/polo-ralph-lauren-icon-logo-short-sleeve-seersucker-shirt-custom-regular-fit-in-indigo-blue/202061272-1-indigoblue?$n_480w$&wid=476&fit=constrain"},
{"name":"Walk London Arrow woven tassel loafers in brown leather","price":"65","color":"BROWN","image":"https://images.asos-media.com/products/walk-london-arrow-woven-tassel-loafers-in-brown-leather/201506442-1-brown?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN loafers in grey velvet floral design with snaffle","price":"34","color":"GREY","image":"https://images.asos-media.com/products/asos-design-loafers-in-grey-velvet-floral-design-with-snaffle/201423365-1-grey?$n_480w$&wid=476&fit=constrain"},{"name":"Noak made in Portugal derby shoes with toe cap in navy suede","price":"95","color":"NAVY","image":"https://images.asos-media.com/products/noak-made-in-portugal-derby-shoes-with-toe-cap-in-navy-suede/202226503-1-navy?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN brogue shoes in brown leather with natural sole and colour details","price":"60","color":"Brown","image":"https://images.asos-media.com/products/asos-design-brogue-shoes-in-brown-leather-with-natural-sole-and-colour-details/13929753-1-brown?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN derby shoes in black suede with piped edging","price":"40","color":"BLACK","image":"https://images.asos-media.com/products/asos-design-derby-shoes-in-black-suede-with-piped-edging/200859618-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN tassel loafers in black faux suede","price":"30","color":"BLACK","image":"https://images.asos-media.com/products/asos-design-tassel-loafers-in-black-faux-suede/200604972-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman black suede colburn loafers","price":"22","color":"BLACK","image":"https://images.asos-media.com/products/topman-black-suede-colburn-loafers/203080976-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN brogue shoes with chunky sole in brown leather","price":"50","color":"BROWN","image":"https://images.asos-media.com/products/asos-design-brogue-shoes-with-chunky-sole-in-brown-leather/200841453-1-brown?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN derby lace up shoe in grey suede on white wedge sole","price":"50","color":"GREY","image":"https://images.asos-media.com/products/asos-design-derby-lace-up-shoe-in-grey-suede-on-white-wedge-sole/201455239-1-grey?$n_480w$&wid=476&fit=constrain"},{"name":"Walk London Riva chain loafers in beige leather","price":"80","color":"NEUTRAL","image":"https://images.asos-media.com/products/walk-london-riva-chain-loafers-in-beige-leather/201587867-1-neutral?$n_480w$&wid=476&fit=constrain"},
{"name":"Nike Victori One sliders in wheat/brown","price":"27","color":"Brown","image":"https://images.asos-media.com/products/nike-victori-one-sliders-in-wheat-brown/201493267-1-brown?$n_480w$&wid=476&fit=constrain"},
{"name":"Schuh Remi lace up derby shoes in brown leather","price":"50","color":"BROWN","image":"https://images.asos-media.com/products/schuh-remi-lace-up-derby-shoes-in-brown-leather/201639493-1-brown?$n_480w$&wid=476&fit=constrain"},{"name":"Schuh Rowen brogues in tan leather","price":"50","color":"BROWN","image":"https://images.asos-media.com/products/schuh-rowen-brogues-in-tan-leather/201640121-1-brown?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN chunky loafer in black faux leather with snaffle detail","price":"45","color":"BLACK","image":"https://images.asos-media.com/products/asos-design-chunky-loafer-in-black-faux-leather-with-snaffle-detail/200899626-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN loafers in brown faux leather on white sole","price":"28","color":"BROWN","image":"https://images.asos-media.com/products/asos-design-loafers-in-brown-faux-leather-on-white-sole/201422930-1-brown?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN loafers in black faux suede with snaffle detail","price":"30","color":"Black","image":"https://images.asos-media.com/products/asos-design-loafers-in-black-faux-suede-with-snaffle-detail/201815002-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Ugg tasman puft slippers in khaki","price":"90","color":"GREEN","image":"https://images.asos-media.com/products/ugg-tasman-puft-slippers-in-khaki/202093901-1-green?$n_480w$&wid=476&fit=constrain"},{"name":"Shaka schlaf padded slipper shoes in tan","price":"129","color":"Tan","image":"https://images.asos-media.com/products/shaka-schlaf-padded-slipper-shoes-in-tan/201387258-1-tan?$n_480w$&wid=476&fit=constrain"},{"name":"Shaka snug slipper shoes in black suede","price":"139","color":"Black","image":"https://images.asos-media.com/products/shaka-snug-slipper-shoes-in-black-suede/201387832-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"New Look suede mule slipper with faux fur in tan","price":"13","color":"Tan","image":"https://images.asos-media.com/products/new-look-suede-mule-slipper-with-faux-fur-in-tan/201368628-1-tan?$n_480w$&wid=476&fit=constrain"},{"name":"Hollister slipper in black with all over logo","price":"25","color":"Black","image":"https://images.asos-media.com/products/hollister-slipper-in-black-with-all-over-logo/201538307-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Ugg scuff sheepskin slippers in black","price":"84","color":"Black","image":"https://images.asos-media.com/products/ugg-scuff-sheepskin-slippers-in-black/24308951-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Shaka snug slipper shoes in tan suede","price":"139","color":"Tan","image":"https://images.asos-media.com/products/shaka-snug-slipper-shoes-in-tan-suede/201388858-1-tan?$n_480w$&wid=476&fit=constrain"},{"name":"Shaka schlaf padded slipper shoes in black","price":"129","color":"Black","image":"https://images.asos-media.com/products/shaka-schlaf-padded-slipper-shoes-in-black/201384325-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Shaka schlaf padded slipper shoes in khaki","price":"129","color":"Khaki","image":"https://images.asos-media.com/products/shaka-schlaf-padded-slipper-shoes-in-khaki/201385280-1-khaki?$n_480w$&wid=476&fit=constrain"},{"name":"Shaka schlaf padded slipper boots in black","price":"149","color":"black","image":"https://images.asos-media.com/products/shaka-schlaf-padded-slipper-boots-in-black/201387508-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"Shaka schlaf padded slipper boots in khaki","price":"149","color":"khaki","image":"https://images.asos-media.com/products/shaka-schlaf-padded-slipper-boots-in-khaki/201387686-1-khaki?$n_480w$&wid=476&fit=constrain"},{"name":"The North Face Thermoball Traction printed slippers in red","price":"50","color":"Red","image":"https://images.asos-media.com/products/the-north-face-thermoball-traction-printed-slippers-in-red/24311858-1-red?$n_480w$&wid=476&fit=constrain"},
{"name":"Hugo slipper in black","price":"99","color":"Black","image":"https://images.asos-media.com/products/hugo-slipper-in-black/201531528-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN slippers in natural borg","price":"20","color":"CAMEL","image":"https://images.asos-media.com/products/asos-design-slippers-in-natural-borg/200912066-1-camel?$n_480w$&wid=476&fit=constrain"},{"name":"Ugg scuff sheepskin slippers in navy","price":"84","color":"Navy","image":"https://images.asos-media.com/products/ugg-scuff-sheepskin-slippers-in-navy/24308976-1-navy?$n_480w$&wid=476&fit=constrain"},
{"name":"Ugg tasman puft slippers in khaki","price":"90","color":"GREEN","image":"https://images.asos-media.com/products/ugg-tasman-puft-slippers-in-khaki/202093901-1-green?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman denim shorts dungaree in washed black","price":"45","color":"Washed Black","image":"https://images.asos-media.com/products/topman-denim-shorts-dungaree-in-washed-black/201705800-1-washedblack?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN skinny jeans in mid wash blue with heavy rips","price":"36","color":"Mid Wash Blue","image":"https://images.asos-media.com/products/asos-design-skinny-jeans-in-mid-wash-blue-with-heavy-rips/202010689-1-midwashblue?$n_480w$&wid=476&fit=constrain"},{"name":"New Look baggy 90s fit jeans in black","price":"25","color":"Black","image":"https://images.asos-media.com/products/new-look-baggy-90s-fit-jeans-in-black/202852332-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Topman stretch taper jeans in black","price":"37","color":"Black","image":"https://images.asos-media.com/products/topman-stretch-taper-jeans-in-black/24536096-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Topman organic cotton blend stretch skinny ripped jeans in black","price":"28","color":"Black","image":"https://images.asos-media.com/products/topman-organic-cotton-blend-stretch-skinny-ripped-jeans-in-black/24555100-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"New Look baggy 90s fit jeans in light blue wash","price":"25","color":"Blue","image":"https://images.asos-media.com/products/new-look-baggy-90s-fit-jeans-in-light-blue-wash/24321534-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"New Look slim rigid jeans in washed black","price":"20","color":"Black","image":"https://images.asos-media.com/products/new-look-slim-rigid-jeans-in-washed-black/23140766-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Sixth June relaxed fit denim jeans in black with all over logo print","price":"69","color":"Black","image":"https://images.asos-media.com/products/sixth-june-relaxed-fit-denim-jeans-in-black-with-all-over-logo-print/201844384-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"COLLUSION Unisex 90s baggy jeans with embroidery in ecru","price":"33","color":"ECRU","image":"https://images.asos-media.com/products/collusion-unisex-90s-baggy-jeans-with-embroidery-in-ecru/201862034-1-ecru?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman organic cotton blend spray on jeans in light wash","price":"32","color":"Blue","image":"https://images.asos-media.com/products/topman-organic-cotton-blend-spray-on-jeans-in-light-wash/24155116-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"Topman slim jeans in stay black","price":"35","color":"Black","image":"https://images.asos-media.com/products/topman-slim-jeans-in-stay-black/200915232-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Jack & Jones Intelligence Liam skinny fit stretch jeans in blue black","price":"37","color":" Blue/Black denim","image":"https://images.asos-media.com/products/jack-jones-intelligence-liam-skinny-fit-stretch-jeans-in-blue-black/202084011-1-blueblackdenim?$n_480w$&wid=476&fit=constrain"},{"name":"Jack & Jones Intelligence Glenn slim tapered fit jeans in mid blue","price":"37","color":"Blue denim","image":"https://images.asos-media.com/products/jack-jones-intelligence-glenn-slim-tapered-fit-jeans-in-mid-blue/202077691-1-bluedenim?$n_480w$&wid=476&fit=constrain"},{"name":"Jack & Jones Intelligence Glenn slim tapered fit jeans in black","price":"37","color":"Black denim","image":"https://images.asos-media.com/products/jack-jones-intelligence-glenn-slim-tapered-fit-jeans-in-black/202077590-1-blackdenim?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN dad jeans in light wash blue with front seam detail","price":"36","color":"Blue","image":"https://images.asos-media.com/products/asos-design-dad-jeans-in-light-wash-blue-with-front-seam-detail/202010729-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"Dr Denim Rush tapered knee ripped jeans in mid wash","price":"58","color":"Blue","image":"https://images.asos-media.com/products/dr-denim-rush-tapered-knee-ripped-jeans-in-mid-wash/202452073-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"Only & Sons Weft regular fit jeans in black wash","price":"40","color":" Black Denim","image":"https://images.asos-media.com/products/only-sons-weft-regular-fit-jeans-in-black-wash/202513278-1-blackdenim?$n_480w$&wid=476&fit=constrain"},
{"name":"Bershka baggy jeans with rips in faded blue","price":"36","color":"Faded blue","image":"https://images.asos-media.com/products/bershka-baggy-jeans-with-rips-in-faded-blue/202914801-1-fadedblue?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN baggy jeans in white with heavy rips","price":"36","color":"White","image":"https://images.asos-media.com/products/asos-design-baggy-jeans-in-white-with-heavy-rips/201661710-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN slim jean in black with elasticated hem","price":"34","color":"Washed black","image":"https://images.asos-media.com/products/asos-design-slim-jean-in-black-with-elasticated-hem/201984674-1-washedblack?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman denim shorts dungaree in washed black","price":"45","color":"Washed Black","image":"https://images.asos-media.com/products/topman-denim-shorts-dungaree-in-washed-black/201705800-1-washedblack?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN skinny jeans in mid wash blue with heavy rips","price":"36","color":"Mid Wash Blue","image":"https://images.asos-media.com/products/asos-design-skinny-jeans-in-mid-wash-blue-with-heavy-rips/202010689-1-midwashblue?$n_480w$&wid=476&fit=constrain"},{"name":"New Look baggy 90s fit jeans in black","price":"25","color":"Black","image":"https://images.asos-media.com/products/new-look-baggy-90s-fit-jeans-in-black/202852332-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Topman stretch taper jeans in black","price":"37","color":"Black","image":"https://images.asos-media.com/products/topman-stretch-taper-jeans-in-black/24536096-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Topman organic cotton blend stretch skinny ripped jeans in black","price":"28","color":"Black","image":"https://images.asos-media.com/products/topman-organic-cotton-blend-stretch-skinny-ripped-jeans-in-black/24555100-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"New Look baggy 90s fit jeans in light blue wash","price":"25","color":"Blue","image":"https://images.asos-media.com/products/new-look-baggy-90s-fit-jeans-in-light-blue-wash/24321534-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"New Look slim rigid jeans in washed black","price":"20","color":"Black","image":"https://images.asos-media.com/products/new-look-slim-rigid-jeans-in-washed-black/23140766-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Sixth June relaxed fit denim jeans in black with all over logo print","price":"69","color":"Black","image":"https://images.asos-media.com/products/sixth-june-relaxed-fit-denim-jeans-in-black-with-all-over-logo-print/201844384-1-black?$n_480w$&wid=476&fit=constrain"},
{"name":"COLLUSION Unisex 90s baggy jeans with embroidery in ecru","price":"33","color":"ECRU","image":"https://images.asos-media.com/products/collusion-unisex-90s-baggy-jeans-with-embroidery-in-ecru/201862034-1-ecru?$n_480w$&wid=476&fit=constrain"},
{"name":"Topman organic cotton blend spray on jeans in light wash","price":"32","color":"Blue","image":"https://images.asos-media.com/products/topman-organic-cotton-blend-spray-on-jeans-in-light-wash/24155116-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"Topman slim jeans in stay black","price":"35","color":"Black","image":"https://images.asos-media.com/products/topman-slim-jeans-in-stay-black/200915232-1-black?$n_480w$&wid=476&fit=constrain"},{"name":"Jack & Jones Intelligence Liam skinny fit stretch jeans in blue black","price":"37","color":" Blue/Black denim","image":"https://images.asos-media.com/products/jack-jones-intelligence-liam-skinny-fit-stretch-jeans-in-blue-black/202084011-1-blueblackdenim?$n_480w$&wid=476&fit=constrain"},{"name":"Jack & Jones Intelligence Glenn slim tapered fit jeans in mid blue","price":"37","color":"Blue denim","image":"https://images.asos-media.com/products/jack-jones-intelligence-glenn-slim-tapered-fit-jeans-in-mid-blue/202077691-1-bluedenim?$n_480w$&wid=476&fit=constrain"},{"name":"Jack & Jones Intelligence Glenn slim tapered fit jeans in black","price":"37","color":"Black denim","image":"https://images.asos-media.com/products/jack-jones-intelligence-glenn-slim-tapered-fit-jeans-in-black/202077590-1-blackdenim?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN dad jeans in light wash blue with front seam detail","price":"36","color":"Blue","image":"https://images.asos-media.com/products/asos-design-dad-jeans-in-light-wash-blue-with-front-seam-detail/202010729-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"Dr Denim Rush tapered knee ripped jeans in mid wash","price":"58","color":"Blue","image":"https://images.asos-media.com/products/dr-denim-rush-tapered-knee-ripped-jeans-in-mid-wash/202452073-1-blue?$n_480w$&wid=476&fit=constrain"},{"name":"Only & Sons Weft regular fit jeans in black wash","price":"40","color":" Black Denim","image":"https://images.asos-media.com/products/only-sons-weft-regular-fit-jeans-in-black-wash/202513278-1-blackdenim?$n_480w$&wid=476&fit=constrain"},
{"name":"Bershka baggy jeans with rips in faded blue","price":"36","color":"Faded blue","image":"https://images.asos-media.com/products/bershka-baggy-jeans-with-rips-in-faded-blue/202914801-1-fadedblue?$n_480w$&wid=476&fit=constrain"},{"name":"ASOS DESIGN baggy jeans in white with heavy rips","price":"36","color":"White","image":"https://images.asos-media.com/products/asos-design-baggy-jeans-in-white-with-heavy-rips/201661710-1-white?$n_480w$&wid=476&fit=constrain"},
{"name":"ASOS DESIGN slim jean in black with elasticated hem","price":"34","color":"Washed black","image":"https://images.asos-media.com/products/asos-design-slim-jean-in-black-with-elasticated-hem/201984674-1-washedblack?$n_480w$&wid=476&fit=constrain"}]






/////
var hairDiv = document.getElementById("containerDiv");

var cartArr = [];

function appendProduct(Mens_Clothing) {
  hairDiv.innerHTML = null;
  Mens_Clothing.forEach(function (elem) {

    let box = document.createElement("div");
    box.setAttribute("id","div111")

    let image = document.createElement("img");
    image.src = elem.image;

    let name = document.createElement("p");
    name.innerText = elem.name;

    let price = document.createElement("p");
    price.innerText = "£"+""+ elem.price+".00"


    box.addEventListener("click", function () {
    //   event.preventDefault();
      cartArr.push(elem);
      localStorage.setItem("asosArr", JSON.stringify(cartArr));
      console.log(cartArr);
      window.location.href="buyProducts.html"
    //   alert("Product added to the cart!");
    })

    box.append(image, name, price);
    hairDiv.append(box);
  });
}

appendProduct(Mens_Clothing);

  
   //    Search Data Text Geeting

   let data = JSON.parse(localStorage.getItem("inpData"))
   console.log(data)

   var sname=document.getElementById("searchByName")
   sname.innerHTML=`Search Result: ${data}`

   //  console.log(searchText);
    var filterdata=Mens_Clothing.filter(function(elem,index){
                 return elem.name.toLowerCase().includes(data);

    })


   appendProduct(filterdata);

     //    search_Function

     let  asosSearchArr=[]
     let searchAsosProd = document.getElementById("searchTextData").addEventListener("keyup",searchAsos);
     function searchAsos(e){
       if(e.key==="Enter"){
        var searchText=document.getElementById("searchTextData").value;
   
        asosSearchArr.push(searchText)
        localStorage.setItem("inpData",JSON.stringify(asosSearchArr))
   
        console.log(searchText);
   
       //  window.Location.href="search.html"
        window.location.href="search.html"
   
       }
   
     }
   
   
 